//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basket
    {
        public Basket()
        {
            this.Basket_items = new HashSet<Basket_items>();
        }
    
        public int id { get; set; }
        public int user_id { get; set; }
    
        public virtual ICollection<Basket_items> Basket_items { get; set; }
        public virtual Users Users { get; set; }
    }
}
