//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SqlEntities : DbContext
    {
        public SqlEntities()
            : base("name=SqlEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Basket> Basket { get; set; }
        public DbSet<Basket_items> Basket_items { get; set; }
        public DbSet<Categories> Categories { get; set; }
        public DbSet<Category_type> Category_type { get; set; }
        public DbSet<Images> Images { get; set; }
        public DbSet<News> News { get; set; }
        public DbSet<News_image> News_image { get; set; }
        public DbSet<Order> Order { get; set; }
        public DbSet<Order_items> Order_items { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<Unit> Unit { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
