//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Basket> Basket { get; set; }
        public virtual DbSet<Basket_items> Basket_items { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Category_type> Category_type { get; set; }
        public virtual DbSet<Images> Images { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<News_image> News_image { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Order_items> Order_items { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Unit> Unit { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
