//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sizes
    {
        public Sizes()
        {
            this.UnitInfo = new HashSet<UnitInfo>();
        }
    
        public int id { get; set; }
        public string size { get; set; }
    
        public virtual ICollection<UnitInfo> UnitInfo { get; set; }
    }
}
