//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitInfo
    {
        public int id { get; set; }
        public int unit_id { get; set; }
        public int size_id { get; set; }
        public int amount { get; set; }


        public bool ExistsSizes(List<int> sizesId)
        {
            bool res = false;
            foreach (var i in sizesId)
            {
                if (size_id == i)
                {
                    res = true;
                }
            }

            return base.Equals(res);
        }

        public virtual Sizes Sizes { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
