//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Basket = new HashSet<Basket>();
            this.Order = new HashSet<Order>();
        }
    
        public int id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string number { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public int role_id { get; set; }
        public System.DateTime reg_date { get; set; }
        public bool is_man { get; set; }
    
        public virtual ICollection<Basket> Basket { get; set; }
        public virtual ICollection<Order> Order { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
